### PR TITLE
MTC head

### PR DESCRIPTION
**Pull request by tbuckl**
@fscottfoti there were no merge conflicts here. it might make sense to try creating a branch on udst to try this merge on so that we can also test out whether branches from mtc merge to it? i would think they would in any case, but since you brought it up.

### CODE REVIEW

**Comment by tombuckley** [comment]
@fscottfoti also here's the git commands in case you just want to do this some other way:

i think we can also push branches over this way. 

```
 mkdir udst
 cd udst
 git clone https://github.com/tombuckley/bayarea_urbansim.git .
 git remote add mtc https://github.com/MetropolitanTransportationCommission/bayarea_urbansim.git
 git branch -b mtc-head
 git checkout -b mtc-head
 git fetch mtc
 git merge mtc/master
 git push origin mtc-head
```

**Comment by tombuckley** [comment]
I think if we merge to UDST and then fork back to MTC, we would have to delete the existing MTC/bayarea_urbansim repository. Thats probably fine, although I think we would might lose a bunch of comments and discussion in the Pull Requests. So how about renaming the MTC/bayarea_urbansim to MTC/bayarea_urbansim_archive? Then merging this PR (or similar), then re-forking to MTC?

**Comment by waddell** [comment]
If you want to do this without losing anything, here is a really simple way.  I delete or rename UDST/bayarea_urbansim, and then Fletcher who is probably an admin on both, can just transfer ownership to UDST.  It shows up there, intact, with everything as it is now.

https://help.github.com/articles/transferring-a-repository/

**Comment by tombuckley** [comment]
apparently, in any case, issues and pulls can be easily backed up: 
`https://www.quora.com/How-can-I-export-backup-GitHub-issues`

**Comment by tombuckley** [comment]
for example:
```
curl https://api.github.com/repos/MetropolitanTransportationCommission/bayarea_urbansim/pulls\?state\=all  
curl https://api.github.com/repos/UDST/bayarea_urbansim/pulls\?state\=all  
curl https://api.github.com/repos/MetropolitanTransportationCommission/bayarea_urbansim/issues\?state\=all  
```

**Comment by fscottfoti** [comment]
Yeah I'm inclined to do it like Paul's suggested but I'm concerned about losing the open PRs and wiki content and issues like Tom says so I want to be careful about it.  I'm also most concerned about the changes that are in the ual fork...

**Comment by tombuckley** [comment]
@fscottfoti looking into the PR/issues backup a bit. not sure its all coming through with the above commands just yet.

**Comment by fscottfoti** [comment]
OK, leaving aside the UAL issue for now, let's resolve the UDST/MTC issue.  To do that I think we should take Tom's approach.  We should merge this PR which brings UDST up to date with MTC's master and then we should re-fork in to MTC.

We should do it that way because there are open PRs on UDST that are still valuable and because it has open issues.  We're lucky because right now at MTC we don't use issues or the wiki, and have only one development branch.  We can basically wipe it away and be fine.  I will take two steps first - download the code just in case something goes wrong and move the only development branch into a gist.

That should make this good from a UDST/MTC perspective and we can then look at UAL.  All in favor say aye!

**Comment by fscottfoti** [comment]
Also, interestingly I don't think there was any way around this issue.  The only thing we could do would be to merge back to the UDST version and delete our repos anyway, which is just as easy to do this way and has all the same problems (losing wiki, issues, and open PRs).  Caveat emptor when forking private repos.

**Comment by tombuckley** [comment]
@fscottfoti ok so in the short-term, we will rename the MTC/bayarea_urbansim repo to _archive and then re-fork from UDST?

then in the long-term hopefully we can just delete it, after reviewing the following to see if everything is archived there?

https://gist.github.com/tombuckley/d9a8bffd35fee2d4e005

**Comment by fscottfoti** [comment]
Cool.  I just did the rename and fork.  Ready to merge this PR?

**Comment by fscottfoti** [comment]
(I also made a back of the MTC repo just in case)

**Comment by waddell** [comment]
Sounds good!

**Comment by waddell** [comment]
Congratulations!  Massive merge accomplished.

**Comment by waddell** [comment]
The UAL repo was forked from the UDST one, so now I think we mainly need to pull these updates into the UAL fork to sync things up.

**Comment by fscottfoti** [comment]
Yeah unfortunately that's not sufficient.  UAL/bayarea_urbansim is no longer a fork of UDST/bayarea_urbansim - it's in the same situation.  You will need to do something like that:

* Take all the PRs you want to keep and open a PR on UDST instead.  @tombuckley will give instructions on how to do that.  Hopefully that's just the `arb` branch.

* Fork from UDST/bayarea_urbansim again.

* Move the wiki updates over manually.

* Rename the UAL/bayarea_urbansim and save it for posterity and make everyone re-clone from the new version which is forked again from UDST.

@tombuckley anything I missed?

Sorry about this!  Like I said before, from my reading I don't think there was any way to avoid this.  It would have been a similar process no matter what.

**Comment by fscottfoti** [comment]
Also, if this sounds complicated it's not that bad.  It could have been a whole lot worse.  Thanks @smmaurer for keeping things organized in a branch!

**Comment by tombuckley** [comment]
@fscottfoti hrm, maybe renaming does not work...seems the old MTC repo is no longer around? well, at least we have that backup of all (i hope!) the pull requests!

**Comment by fscottfoti** [comment]
Renaming does work.  @mkreilly moved it to his personal repo to avoid confusion.  Everything is going according to plan!

**Comment by fscottfoti** [comment]
@waddell Can you get everyone organized to move all the UAL changes into a single branch, or give us a list of branches you want to preserve (merging in any local changes!)?  We can then have @tombuckley open them as PRs on UDST/bayarea_urbansim so you guys can fork again.  This can be done at whatever time you want - there's no hurry if you have work in progress.  How does that sound?

**Comment by tombuckley** [comment]
@fscottfoti @waddell happy to help. let me know who i should speak with.

**Comment by waddell** [comment]
Outstanding. Thanks for all the help!

It is spring break this week so might be tricky to get this organized but I'll send out the notices to get started.  And yes, it might take a bit of help to sync these up.

**Comment by mkreilly** [comment]
hey aren't grad students supposed to sit in your lab and work all spring break? ;)

**Comment by waddell** [comment]
Right!  I'm sure they are there, pounding away.

**Comment by smmaurer** [comment]
Hi @fscottfoti and @tombuckley, thanks for the help! I'm finding out which branches we need to preserve from UAL/bayarea_urbansim, but it may take a little while for people to get back to me. We've been using the wiki, but not issues or pull requests. 

I don't quite understand how the branch preservation works, though. Is it that we open PR's to copy the branches over to UDST/bayarea_urbansim, and then they'll be there when we re-fork? Thanks!

**Comment by tombuckley** [comment]
@smmaurer sorry i'm not exactly sure how branch preservation works in this case either! however, i do see that you have done some work, for example here: https://github.com/ual/bayarea_urbansim/tree/rental-hedonics that looks like it might be useful. my preference would be that useful work gets merged into some single master branch. i realize that is vague, but maybe this closed Pull Request here is a case study of that goal?

**Comment by waddell** [comment]
Hey, @tombuckley, our work is *all* useful!  Some just more useful than other...

**Comment by tombuckley** [comment]
@smmaurer on the other hand, mechanically, we could just pull your rental-hedonics branch from ual and push it to udst. or we can just leave it on ual until its ready to be merged into master.

**Comment by fscottfoti** [comment]
Yes, that's what we're hoping to do, and the fewer branches we have the better I think, though it doesn't have to be down to 1 branch.  It will tough because unlike the other one, there are bound to be conflicts.

**Pull request merged**
